### ISSUE TITLE
Cannot use - in keys

### ISSUE THREAD

**Issue by mcaulifn** [jmespath/jmespath.py#141]
RPC calls to a device output a specific JSON formatted object. The keys have -'s in them.

```json
{
    "ike-security-associations-information": [
        {
            "ike-security-associations": [
                {
                    "ike-sa-exchange-type": [
                        {
                            "data": "main"
                        }
                    ],
                    "ike-sa-initiator-cookie": [
                        {
                            "data": "a16a3dc60b4f87be"
                        }
                    ],
                    "ike-sa-remote-address": [
                        {
                            "data": "10.41.183.51"
                        }
                    ],
                    "ike-sa-index": [
                        {
                            "data": "799947"
                        }
                    ],
                    "ike-sa-state": [
                        {
                            "data": "UP"
                        }
                    ],
                    "ike-sa-responder-cookie": [
                        {
                            "data": "1e61640de1c4e60e"
                        }
                    ]
                },
                {
                    "ike-sa-exchange-type": [
                        {
                            "data": "main"
                        }
                    ],
                    "ike-sa-initiator-cookie": [
                        {
                            "data": "3b872f48472eac0a"
                        }
                    ],
                    "ike-sa-remote-address": [
                        {
                            "data": "10.37.93.216"
                        }
                    ],
                    "ike-sa-index": [
                        {
                            "data": "799948"
                        }
                    ],
                    "ike-sa-state": [
                        {
                            "data": "UP"
                        }
                    ],
                    "ike-sa-responder-cookie": [
                        {
                            "data": "6e936156f0451000"
                        }
                    ]
                },
                {
                    "ike-sa-exchange-type": [
                        {
                            "data": "main"
                        }
                    ],
                    "ike-sa-initiator-cookie": [
                        {
                            "data": "9add93f2e404bee3"
                        }
                    ],
                    "ike-sa-remote-address": [
                        {
                            "data": "10.39.41.228"
                        }
                    ],
                    "ike-sa-index": [
                        {
                            "data": "799949"
                        }
                    ],
                    "ike-sa-state": [
                        {
                            "data": "UP"
                        }
                    ],
                    "ike-sa-responder-cookie": [
                        {
                            "data": "b397214e0189d0f2"
                        }
                    ]
                },
                {
                    "ike-sa-exchange-type": [
                        {
                            "data": "main"
                        }
                    ],
                    "ike-sa-initiator-cookie": [
                        {
                            "data": "b7f987841c7bf344"
                        }
                    ],
                    "ike-sa-remote-address": [
                        {
                            "data": "10.36.39.218"
                        }
                    ],
                    "ike-sa-index": [
                        {
                            "data": "799950"
                        }
                    ],
                    "ike-sa-state": [
                        {
                            "data": "UP"
                        }
                    ],
                    "ike-sa-responder-cookie": [
                        {
                            "data": "0628b635c76912fe"
                        }
                    ]
                },
                {
                    "ike-sa-exchange-type": [
                        {
                            "data": "main"
                        }
                    ],
                    "ike-sa-initiator-cookie": [
                        {
                            "data": "3b128c4735176d5d"
                        }
                    ],
                    "ike-sa-remote-address": [
                        {
                            "data": "10.37.75.77"
                        }
                    ],
                    "ike-sa-index": [
                        {
                            "data": "799951"
                        }
                    ],
                    "ike-sa-state": [
                        {
                            "data": "UP"
                        }
                    ],
                    "ike-sa-responder-cookie": [
                        {
                            "data": "f8cbbc6a60448073"
                        }
                    ]
                },
                {
                    "ike-sa-exchange-type": [
                        {
                            "data": "main"
                        }
                    ],
                    "ike-sa-initiator-cookie": [
                        {
                            "data": "0e359c0537b8d2bb"
                        }
                    ],
                    "ike-sa-remote-address": [
                        {
                            "data": "10.165.186.90"
                        }
                    ],
                    "ike-sa-index": [
                        {
                            "data": "799952"
                        }
                    ],
                    "ike-sa-state": [
                        {
                            "data": "UP"
                        }
                    ],
                    "ike-sa-responder-cookie": [
                        {
                            "data": "7c3892ce4784ec78"
                        }
                    ]
                }
            ],
            "attributes": {
                "junos:style": "brief"
            }
        }
    ]
}
```

```
>>> search_string = jmespath.search('ike-security-associations', ike_json)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/jmespath/__init__.py", line 12, in search
    return parser.Parser().parse(expression).search(data, options=options)
  File "/usr/lib/python2.7/dist-packages/jmespath/parser.py", line 87, in parse
    parsed_result = self._do_parse(expression)
  File "/usr/lib/python2.7/dist-packages/jmespath/parser.py", line 95, in _do_parse
    return self._parse(expression)
  File "/usr/lib/python2.7/dist-packages/jmespath/parser.py", line 108, in _parse
    self._tokens = list(self.tokenizer)
  File "/usr/lib/python2.7/dist-packages/jmespath/lexer.py", line 71, in tokenize
    yield {'type': 'number', 'value': int(buff),
ValueError: invalid literal for int() with base 10: '-'
```

**Comment by georgeyk** [comment]
This issue was discussed here: https://github.com/jmespath/jmespath.py/issues/109

**Comment by Akasurde** [comment]
@mcaulifn Try this - 

```
from jmespath import search
import json
null = None
a = json.load(open("localhost.json", "r"))
print(search('"ike-security-associations-information"', a))
```
