### ISSUE TITLE
Index expression following filter expression fails

### ISSUE THREAD

**Issue by bhyde** [jmespath/jmespath.py#91]
Is this a bug?  I.e. ```search('[0]', search('[?a==`1`].a', x))``` works, but ```search('[?a==`1`].a.[0]', x)``` doesn't.

```
$ python
Python 2.7.10 (default, Jul 25 2015, 21:04:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from jmespath import search
>>> from json import loads
>>> x = loads('[{"a":1}]')
>>> search('[?a==`1`]', x)
[{u'a': 1}]
>>> search('[0]', search('[?a==`1`].a', x))
1
>>> search('[?a==`1`].a.[0]', x)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/__init__.py", line 11, in search
    return parser.Parser().parse(expression).search(data)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 81, in parse
    parsed_result = self._do_parse(expression)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 89, in _do_parse
    return self._parse(expression)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 104, in _parse
    parsed = self._expression(binding_power=0)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 117, in _expression
    left = nud_function(left_token)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 159, in _token_nud_filter
    return self._token_led_filter(ast.identity())
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 280, in _token_led_filter
    right = self._parse_projection_rhs(self.BINDING_POWER['filter'])
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 381, in _parse_projection_rhs
    right = self._parse_dot_rhs(binding_power)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 403, in _parse_dot_rhs
    return self._expression(binding_power)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 126, in _expression
    left = led(left)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 236, in _token_led_dot
    right = self._parse_dot_rhs(self.BINDING_POWER['dot'])
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 406, in _parse_dot_rhs
    return self._parse_multi_select_list()
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 342, in _parse_multi_select_list
    expression = self._expression()
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 117, in _expression
    left = nud_function(left_token)
  File "/home/bhyde/.pyenv/versions/2.7.10/lib/python2.7/site-packages/jmespath/parser.py", line 437, in _error_nud_token
    token['type'], 'Invalid token.')
jmespath.exceptions.ParseError: Invalid token.: Parse error at column 13, token "0" (NUMBER), for expression:
"[?a==`1`].a.[0]"
              ^
>>> 
```

ps. Jmespath is very cool and useful.

**Comment by bhyde** [comment]
I see now, that I have read the end of the spec and know about pipe expressions, that was what I wanted for my use case.  And that the backtrace is telling me that the elements of the projection aren't an array.

**Comment by jamesls** [comment]
Awesome, I'm glad you were able to figure it out.  Let me know if you have any more questions.
